
When Catching exceptions, we should catch the most specific first. 
Then the last one becomes a catch-all; 

try
{
    var calculator = new Calculator();
    var result = calculator.Calculate(number1, number2, operation);

    DisplayResult(result);
}
catch (ArgumentNullException ex)
{
    //Log.Error(ex);
    WriteLine($"Operation was not provided. {ex}");
}
catch (ArgumentOutOfRangeException ex)
{
    //Log.Error(ex);
    WriteLine($"Operation is not supported. {ex}");
}
catch (Exception ex)
{
    WriteLine($"Sorry, something went wrong. {ex}");
}


